# Generated by Django 4.2.4 on 2023-10-13 06:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_profile', '0002_profile_location'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shippingfee',
            name='location',
            field=models.CharField(max_length=200, unique=True),
        ),
    ]
