# Generated by Django 4.2.4 on 2023-10-13 18:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_profile', '0004_profile_transfer_description'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='transfer_description',
        ),
    ]
