# Generated by Django 4.2.4 on 2023-10-14 13:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog_app', '0003_alter_blog_post_cover_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog_post',
            name='cover_photo',
            field=models.URLField(blank=True, help_text='attach image url from cloudinary', null=True),
        ),
    ]
