# Generated by Django 4.2.4 on 2023-10-13 06:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('company_details', '0002_ccount_details_delete_account_details'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ccount_details',
            new_name='Acount_details',
        ),
    ]
