# Generated by Django 4.2.4 on 2023-10-13 06:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('company_details', '0003_rename_ccount_details_acount_details'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Acount_details',
            new_name='Account_details',
        ),
    ]
