# Generated by Django 4.2.4 on 2023-10-13 07:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company_details', '0005_alter_account_details_account_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='account_details',
            name='date',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
