# Generated by Django 4.2.4 on 2023-10-13 07:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company_details', '0006_account_details_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contact_details',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('phone_number', models.CharField(max_length=20)),
                ('whatsapp_number', models.CharField(max_length=20)),
                ('email', models.CharField(max_length=100)),
                ('position', models.CharField(help_text='ender position. e.g admin, delivery-personel etc', max_length=200)),
            ],
        ),
    ]
