# Generated by Django 4.2.4 on 2023-10-13 07:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company_details', '0007_contact_details'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contact_detail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('whatsapp_number', models.CharField(max_length=20)),
                ('email', models.CharField(max_length=100)),
                ('position', models.CharField(help_text='ender position. e.g admin, delivery-personel etc', max_length=200)),
            ],
        ),
        migrations.RenameModel(
            old_name='Account_details',
            new_name='Account_detail',
        ),
        migrations.DeleteModel(
            name='Contact_details',
        ),
    ]
