# Generated by Django 4.2.4 on 2023-10-13 07:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company_details', '0008_contact_detail_rename_account_details_account_detail_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='account_detail',
            name='is_active',
            field=models.BooleanField(default=False),
        ),
    ]
