# Generated by Django 4.2.4 on 2023-10-14 17:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company_details', '0010_terms_and_condition'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact_detail',
            name='is_major',
            field=models.BooleanField(default=False),
        ),
    ]
