# Generated by Django 4.2.4 on 2023-10-11 01:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('checkout', '0002_order_shipping_fee_order_total_item_price'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='shipping_fee',
        ),
        migrations.RemoveField(
            model_name='order',
            name='total_item_price',
        ),
    ]
