# Generated by Django 4.2.4 on 2023-10-13 06:06

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('checkout', '0007_order_phone_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='description',
            field=models.UUIDField(default=uuid.uuid4, editable=False),
        ),
    ]
