# Generated by Django 4.2.4 on 2023-10-13 06:15

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('checkout', '0010_order_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='description',
            field=models.UUIDField(default=uuid.uuid4),
        ),
    ]
