# Generated by Django 4.2.4 on 2023-10-13 06:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checkout', '0011_alter_order_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='description',
            field=models.UUIDField(blank=True, null=True),
        ),
    ]
